version: "3"

networks:
    development:
        external: false

services:
    gitea:
        image: gitea/gitea:latest
        environment:
            - USER_UID=1000
            - USER_GID=1000
        restart: always
        networks:
            - development
        volumes:
            - /vagrant/gitea:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "3000:3000"
            - "2222:22"

    registry:
        image: registry:2.7.0
        ports:
            - "5000:5000"
        volumes:
            - /vagrant/registry/data:/var/lib/registry
        restart: always
        networks:
            - development
        environment:
            - REGISTRY_STORAGE_DELETE_ENABLED=true

    nginx:
        image: "nginx:alpine"
        ports:
            - "5043:443"
        links:
            - registry:registry
        volumes:
            - /vagrant/registry/nginx/:/etc/nginx/conf.d
            - /vagrant/registry/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        restart: always
        networks:
            - development

    jenkins:
        container_name: jenkins-master
        restart: always
        environment:
            - JAVA_OPTS="-Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true"
        ports:
            - "8080:8080"
            - "50000:50000"
        image: jenkins-master
        networks:
          - development
        extra_hosts:
            - "kubernetes:${OUTSIDE}"

    jenkins-slave:
        container_name: jenkins-slave
        restart: always
        links:
            - jenkins:jenkins
        environment:
            - "JENKINS_URL=http://jenkins:8080"
        image: jenkins-slave
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /home/jenkins:/home/jenkins
        depends_on:
            - jenkins
        networks:
          - development
        extra_hosts:
            - "kubernetes:${OUTSIDE}"
