# init script
$init = <<SCRIPT
#!/bin/bash

sudo apt -y update
sudo apt install -y curl gnupg2
SCRIPT

# Docker
$docker = <<SCRIPT
#!/bin/bash

sudo apt install -y apt-transport-https ca-certificates software-properties-common
curl https://download.docker.com/linux/debian/gpg | sudo apt-key add -
echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee -a /etc/apt/sources.list.d/docker.list
sudo apt update
sudo apt install -y docker-ce docker-ce-cli
sudo systemctl enable docker
sudo systemctl start docker
sudo usermod -aG docker vagrant
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.hostname = "docker"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "shell", inline: $init, privileged: false
  config.vm.provision "shell", inline: $docker, privileged: false

  config.vbguest.auto_update = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
end
