# init script
$init = <<SCRIPT
#!/bin/bash

sudo apt -y update
sudo apt install -y openjdk-11-jdk-headless gnupg2 curl
SCRIPT

# Jenkins
$jenkins = <<SCRIPT
#!/bin/bash

# https://pkg.jenkins.io/debian-stable/
curl https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
echo "deb https://pkg.jenkins.io/debian-stable binary/" | sudo tee -a /etc/apt/sources.list.d/jenkins.list

sudo apt -y update
sudo apt install -y jenkins

sudo systemctl enable jenkins
sudo systemctl start jenkins
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.hostname = "jenkins"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "shell", inline: $init, privileged: false
  config.vm.provision "shell", inline: $jenkins, privileged: false

  config.vm.network :forwarded_port, guest: 8080, host: 8080

  config.vbguest.auto_update = false
end
